spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:23306/staffjoydb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  port: 8082

staffjoy:
  email-service-endpoint: http://localhost:8088
  account-service-endpoint: http://localhost:8081
  bot-service-endpoint: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"